services:
  go_app:
    container_name: gogym
    environment: 
      DATABASE_URL: "host=go_db user=${DB_USER} dbname=${DB_NAME} password=${DB_PASSWORD} sslmode=disable"
    tty: true
    build: .
    ports:
      - 8000:8000
    restart: on-failure
    depends_on:
      - go_db
    healthcheck:
      test: "curl -f http://localhost/healthcheck"
    networks:
        - go-network

  go_db:
    image: postgres:latest
    restart: always
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
        - go-network

volumes:
  pg_data: {}

networks:
  go-network:
    driver: bridge
